---
services:

  controller:
    environment:
      KAFKA_AUTHORIZER_CLASS_NAME: $KAFKA_AUTHORIZER_CLASS_NAME
      KAFKA_SUPER_USERS: User:broker;User:client;User:controlcenter;User:connect;User:schemaregistry;User:ksqldb;User:controller;User:ANONYMOUS

  broker:
    environment:
      # FIXTHIS:
      # org.apache.kafka.common.KafkaException: Class io.confluent.metrics.reporter.ConfluentMetricsReporter cannot be found
      KAFKA_METRIC_REPORTERS: ""

  broker2:
    environment:
      # FIXTHIS:
      # org.apache.kafka.common.KafkaException: Class io.confluent.metrics.reporter.ConfluentMetricsReporter cannot be found
      KAFKA_METRIC_REPORTERS: ""
  broker3:
    environment:
      # FIXTHIS:
      # org.apache.kafka.common.KafkaException: Class io.confluent.metrics.reporter.ConfluentMetricsReporter cannot be found
      KAFKA_METRIC_REPORTERS: ""