---
services:
  connect:
    volumes:
      - ../../connect/connect-aws-cloudwatch-logs-source/awscredentialsprovider/target/awscredentialsprovider-1.0.0-jar-with-dependencies.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-aws-cloudwatch-logs/lib/awscredentialsprovider-1.0.0-jar-with-dependencies.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-aws-cloudwatch-logs
      AWS_REGION: $AWS_REGION