---
services:

  sql-datagen:
    build:
      context: ../../connect/connect-jdbc-oracle11-source/oracle-datagen/
    hostname: sql-datagen
    container_name: sql-datagen
    profiles:
    - sql_datagen
    volumes:
      - ../../connect-jdbc-oracle11-source/oracle-datagen/target/sql-datagen-1.0-SNAPSHOT-jar-with-dependencies.jar:/sql-datagen-1.0-SNAPSHOT-jar-with-dependencies.jar

  oracle:
    # https://github.com/wnameless/docker-oracle-xe-11g
    image: wnameless/oracle-xe-11g-r2
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
    volumes:
      - ../../connect/connect-jdbc-oracle11-source/00-oracle-init.sql:/docker-entrypoint-initdb.d/00-oracle-init.sql
    environment:
      ORACLE_ALLOW_REMOTE: "true"

  connect:
    depends_on:
      - oracle
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc