---
services:
  connect:
    volumes:
      - ../../connect/connect-azure-event-hubs-source/data:/data
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-azure-event-hubs

  simple-send:
    build:
      context: ../../connect/connect-azure-event-hubs-source/simple-send/
      args:
        CP_CONNECT_TAG: ${CP_CONNECT_TAG}
        CP_CONNECT_IMAGE: ${CP_CONNECT_IMAGE}
        KAFKA_CLIENT_TAG: ${KAFKA_CLIENT_TAG}
    hostname: simple-send
    container_name: simple-send
    depends_on:
      - broker