---
services:
  oracle:
    # https://github.com/wnameless/docker-oracle-xe-11g
    image: wnameless/oracle-xe-11g-r2
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
    volumes:
      - ../../connect/connect-jdbc-oracle11-sink/00-oracle-init.sql:/docker-entrypoint-initdb.d/00-oracle-init.sql
      - ../../connect/connect-jdbc-oracle11-sink/01-create-table.sh:/docker-entrypoint-initdb.d/01-create-table.sh
    environment:
      ORACLE_ALLOW_REMOTE: "true"

  connect:
    depends_on:
      - oracle
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc