---
services:

  jms-client:
    build:
      context: ../../other/jms-client/jms-client/
      args:
        CP_CONNECT_TAG: ${CP_CONNECT_TAG}
        CP_CONNECT_IMAGE: ${CP_CONNECT_IMAGE}
        KAFKA_CLIENT_TAG: ${KAFKA_CLIENT_TAG}
    hostname: jms-client
    container_name: jms-client
    depends_on:
      - broker

  connect:
    entrypoint: ["echo", "Service connect disabled"]