---
services:

  zookeeper:
    image: ${CP_ZOOKEEPER_IMAGE}:${CP_ZOOKEEPER_TAG}
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # for 5.4.x:
      KAFKA_OPTS: -Dzookeeper.4lw.commands.whitelist=*

  broker1:
    image: ${CP_KAFKA_IMAGE}:${CP_KAFKA_TAG}
    hostname: broker1
    container_name: broker1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:9092
      KAFKA_METRIC_REPORTERS: $KAFKA_METRIC_REPORTERS
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1:9092,broker2:9092,broker3:9092
      KAFKA_MESSAGE_MAX_BYTES: 10048588


  broker2:
    image: ${CP_KAFKA_IMAGE}:${CP_KAFKA_TAG}
    hostname: broker2
    container_name: broker2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:9092
      KAFKA_METRIC_REPORTERS: $KAFKA_METRIC_REPORTERS
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1:9092,broker2:9092,broker3:9092
      KAFKA_MESSAGE_MAX_BYTES: 10048588


  broker3:
    image: ${CP_KAFKA_IMAGE}:${CP_KAFKA_TAG}
    hostname: broker3
    container_name: broker3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:9092
      KAFKA_METRIC_REPORTERS: $KAFKA_METRIC_REPORTERS
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1:9092,broker2:9092,broker3:9092
      KAFKA_MESSAGE_MAX_BYTES: 10048588

  schema-registry:
    image: ${CP_SCHEMA_REGISTRY_IMAGE}:${CP_SCHEMA_REGISTRY_TAG}
    hostname: schema-registry
    container_name: schema-registry
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:9092

  # connect is used to launch mirrormaker 2 executable
  connect:
    entrypoint: ["sh", "-c", "sleep 2073600"]
    volumes:
        - ../../ccloud/mirrormaker2/connect-log4j.properties:/tmp/connect-log4j.properties
    environment:
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/tmp/connect-log4j.properties"