organization:
  name: conduktor

database:
  hosts: 
   - host: 'conduktor-postgresql'
     port: 5432
  name: 'conduktor'
  username: 'conduktor'
  password: 'change_me'
  connection_timeout: 30 # in seconds

monitoring:
  cortex-url: 'http://conduktor-monitoring:9009/'
  alert-manager-url: 'http://conduktor-monitoring:9010/'
  callback-url: 'http://conduktor-console:8080/monitoring/api/'
  notifications-callback-url: 'http://localhost:8080'

clusters:
  - id: local
    name: My Cluster
    color: "#0013E7"
    ignoreUntrustedCertificate: true
    bootstrapServers: "broker:9092"
    properties: |
      client.id=conduktor
      default.api.timeout.ms=15000
      request.timeout.ms=5000
      ssl.truststore.location=/etc/kafka/secrets/kafka.conduktor.truststore.jks
      ssl.truststore.password=confluent
      ssl.truststore.type=JKS
      ssl.keystore.location=/etc/kafka/secrets/kafka.conduktor.keystore.jks
      ssl.keystore.password=confluent
      ssl.keystore.type=JKS
      ssl.key.password=confluent
      sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="/var/lib/secret/kafka-controlcenter.key" principal="controlcenter@TEST.CONFLUENT.IO";
      sasl.mechanism=GSSAPI
      security.protocol=SASL_SSL
      sasl.kerberos.service.name=kafka
    schemaRegistry:
      id: Local SR
      url: "http://schema-registry:8081"
      ignoreUntrustedCertificate: true
      properties: |
        acks=all
        client.id=conduktor
        default.api.timeout.ms=15000
        request.timeout.ms=5000
        schema.registry.ssl.truststore.location=/etc/kafka/secrets/kafka.conduktor.truststore.jks
        schema.registry.ssl.truststore.password=confluent
        schema.registry.ssl.keystore.location=/etc/kafka/secrets/kafka.conduktor.keystore.jks
        schema.registry.ssl.keystore.password=confluent
        schema.registry.ssl.key.password=confluent 
    labels:
      env: default
    kafkaConnects:
      - url: "http://connect:8083"
        id: kafka-connect
        name: kafkaConnect
        ignoreUntrustedCertificate: true
