organization:
  name: conduktor

database:
  hosts: 
   - host: 'conduktor-postgresql'
     port: 5432
  name: 'conduktor'
  username: 'conduktor'
  password: 'change_me'
  connection_timeout: 30 # in seconds

monitoring:
  cortex-url: 'http://conduktor-monitoring:9009/'
  alert-manager-url: 'http://conduktor-monitoring:9010/'
  callback-url: 'http://conduktor-console:8080/monitoring/api/'
  notifications-callback-url: 'http://localhost:8080'
clusters:
  - id: local
    name: My Cluster
    color: "#0013E7"
    ignoreUntrustedCertificate: false
    bootstrapServers: "broker:9092"
    properties: |
      client.id=conduktor
      default.api.timeout.ms=15000
      request.timeout.ms=5000
      sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="client" password="client-secret";
      sasl.mechanism=PLAIN
      security.protocol=SASL_PLAINTEXT
    schemaRegistry:
      id: Local SR
      url: "http://schema-registry:8081"
      ignoreUntrustedCertificate: false
      properties: |
        acks=all
        client.id=conduktor
        default.api.timeout.ms=15000
        request.timeout.ms=5000
    labels:
      env: default
    kafkaConnects:
      - url: "http://connect:8083"
        id: kafka-connect
        name: kafkaConnect

