---
services:

  broker:
    environment:
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 30000


  producer:
    build:
      context: ../../troubleshooting/small-retention/producer/
      args:
        CP_CONNECT_TAG: ${CP_CONNECT_TAG}
        CP_CONNECT_IMAGE: ${CP_CONNECT_IMAGE}
        KAFKA_CLIENT_TAG: ${KAFKA_CLIENT_TAG}
    hostname: producer
    container_name: producer
    depends_on:
      - broker
