---
services:
  couchbase:
    image: couchbase # https://hub.docker.com/_/couchbase
    hostname: couchbase
    container_name: couchbase
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"

  connect:
    depends_on:
      - couchbase
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/couchbase-kafka-connect-couchbase

  json-producer:
    build:
      context: ../../connect/connect-couchbase-sink/json-producer/
      args:
        CP_CONNECT_TAG: ${CP_CONNECT_TAG}
        CP_CONNECT_IMAGE: ${CP_CONNECT_IMAGE}
        KAFKA_CLIENT_TAG: ${KAFKA_CLIENT_TAG}
    hostname: json-producer
    container_name: json-producer