---
services:
  simple-send:
    build:
      context: ../../ccloud/fm-azure-event-hubs-source/simple-send/
      args:
        CP_CONNECT_TAG: ${CP_CONNECT_TAG}
        CP_CONNECT_IMAGE: ${CP_CONNECT_IMAGE}
        KAFKA_CLIENT_TAG: ${KAFKA_CLIENT_TAG}
    hostname: simple-send
    container_name: simple-send