---
services:

  vertica:
    image: cjonesy/docker-vertica
    #image: cjonesy/docker-vertica # in order to use vertica db 10, build your own docker image as described here https://github.com/cjonesy/docker-vertica
    hostname: vertica
    container_name: vertica
    ports:
      - 5433:5433

  connect:
    depends_on:
      - vertica
    volumes:
        - ../../connect/connect-jdbc-vertica-sink/vertica-jdbc.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib/vertica-jdbc.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc
