---
services:

  connect:
    volumes:
        - ../../other/control-center-readonly-mode/connect.jaas:/tmp/connect.jaas
        - ../../other/control-center-readonly-mode/connect.password:/tmp/connect.password
    environment:
      CONNECT_REST_EXTENSION_CLASSES: org.apache.kafka.connect.rest.basic.auth.extension.BasicAuthSecurityRestExtension
      KAFKA_OPTS: -Djava.security.auth.login.config=/tmp/connect.jaas

  control-center:
    volumes:
      - ../../other/control-center-readonly-mode/login.properties:/tmp/login.properties
      - ../../other/control-center-readonly-mode/jaas_config.file:/tmp/jaas_config.file
      - ../../other/control-center-readonly-mode/jaas_config_8_plus.file:/tmp/jaas_config_8_plus.file
    environment:
      CONTROL_CENTER_REST_AUTHENTICATION_ROLES: Administrators,Restricted
      CONTROL_CENTER_AUTH_RESTRICTED_ROLES: Restricted
      CONTROL_CENTER_REST_AUTHENTICATION_METHOD: BASIC
      CONTROL_CENTER_REST_AUTHENTICATION_REALM: c3
      CONTROL_CENTER_OPTS: -Djava.security.auth.login.config=$JAAS_CONFIG_FILE